### ISSUE TITLE
Breaks IE11 (which is supported by docsify v4)

### ISSUE THREAD

**Issue by jhildenbiddle** [njleonzhang/docsify-plugin-codefund#6]
This plugin is using [ES2015 method definition shorthand syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) which is not supported by IE11:

https://github.com/njleonzhang/docsify-plugin-codefund/blob/4438c6cbd6d334a0916876d7468999465b562553/index.js#L17-L28

Since IE11 is [officially support by docsify](http://localhost:8080/#/?id=features), docsify plugins should be authored using only ES5 or transpiled from ES6+ to ES5 using a tool like [Babel](https://babeljs.io/). This plugin is used on [docsify.js.org](https://docsify.js.org/) which fails to load properly in IE11 as a result of this issue.

Thanks!

**Comment by kirbyfern** [comment]
Since method definitions are not valid in IE11, it should be
```
    injectCodeFundContainer: function() {
      if (document.getElementById("codefund") === null) {
        let nav = document.getElementsByClassName('sidebar-nav');
        let codefundContainer = document.createElement('div');
        codefundContainer.id = 'codefund';
        nav[0].insertBefore(codefundContainer, nav[0].firstChild);
      }
      
      if (document.getElementsByClassName('cf-wrapper').length === 0) {
        window._codefund && window._codefund.serve();
      }
    },
```
Made a PR at #7.

**Comment by njleonzhang** [comment]
fixed in newest version, thanks

**Comment by jhildenbiddle** [comment]
Thanks @njleonzhang!
